server:
  port:
    8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/g-aleprojetos/DIO/tree/main/Bootcamps/Santander/microsservi%C3%A7os%20usando%20Spring%20Cloud/dio-experts-config